name: Run linter and tests on pull requests

on:
  pull_request:
    branches: [master, main]

env:
  PYTHON_DEFAULT_VERSION: "3.9"

jobs:
{%- if cookiecutter.ci_use_spellchecker == "y" %}
  spellchecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check spelling
        uses: codespell-project/actions-codespell@2391250ab05295bddd51e36a8c6295edb6343b0e
        with:
          ignore_words_list: datas
{%- endif %}
{%- if cookiecutter.ci_use_linter == "y" %}
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python {% raw %}${{ env.PYTHON_DEFAULT_VERSION }}{% endraw %}
        uses: actions/setup-python@v4
        with:
          python-version: {% raw %}${{ env.PYTHON_DEFAULT_VERSION }}{% endraw %}
          cache: "pip"
      - name: Install dependencies
        run: python -m pip install --upgrade nox pip setuptools
      - name: Run linters
        run: nox -vs lint
      - name: Run readable
        run: nox -vs readable
{%- endif %}
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python {% raw %}${{ env.PYTHON_DEFAULT_VERSION }}{% endraw %}
        uses: actions/setup-python@v4
        with:
          python-version: {% raw %}${{ env.PYTHON_DEFAULT_VERSION }}{% endraw %}
          cache: "pip"
      - name: Prepare environment
        run: ./setup-dev.sh
      - name: Install dependencies
        run: python -m pip install --upgrade nox pip setuptools
      - name: Run dockerized services
        run: docker compose up -d --wait
      - name: Run migrations
        run: cd app/src && python manage.py wait_for_database --timeout 120 && python manage.py migrate
      - name: Run unit tests
        run: nox -vs test
      - name: Stop dockerized services
        if: success() || failure()
        run: docker compose down -v
